import { ItineraryOption } from '@/types';

// Helper function to create itinerary options
const createItinerary = (
  id: string,
  name: string,
  days: number,
  description: string,
  itinerary: any[]
): ItineraryOption => ({
  id,
  name,
  days,
  description,
  itinerary,
});

//============================================================================
// 1. LANGTANG TREK ITINERARIES
//============================================================================
export const langtangItineraries: ItineraryOption[] = [
  createItinerary(
    'langtang-7day',
    '7-Day Standard Itinerary',
    7,
    'Classic Langtang Valley trek with optimal acclimatization',
    [
      {
        day: 1,
        title: 'Kathmandu to Syabrubesi (1,450m)',
        description: 'Scenic drive from Kathmandu through winding mountain roads, passing traditional Tamang and Sherpa villages. Cross the Trishuli River and climb through terraced hills offering views of Ganesh Himal, Langtang, and Manaslu ranges. The journey takes you through Dhunche, the district headquarters of Rasuwa.',
        altitude: '1,450m',
        duration: '7-8 hours drive',
        meals: 'Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 2,
        title: 'Syabrubesi to Lama Hotel (2,380m)',
        description: 'Trek begins following the Langtang Khola through subtropical forests. Cross several suspension bridges over the roaring river. The trail climbs through dense forests of oak, maple, and rhododendron. Watch for wildlife including red pandas, langur monkeys, and various bird species. Pass through Bamboo village before reaching Lama Hotel.',
        altitude: '2,380m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 3,
        title: 'Lama Hotel to Langtang Village (3,430m)',
        description: 'Continue ascending through beautiful mixed forests with occasional glimpses of Langtang Lirung (7,227m). The trail gradually opens up as you reach Ghoda Tabela, a former Tibetan refugee settlement. Views become more spectacular as you approach Langtang village. Pass through the rebuilt village and see the memorial stupa for 2015 earthquake victims. First clear views of Langtang Lirung, Langtang II, and other peaks.',
        altitude: '3,430m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 4,
        title: 'Langtang Village to Kyanjin Gompa (3,870m)',
        description: 'Walk through yak pastures and traditional stone houses decorated with prayer flags. Pass numerous mani walls and chortens as you enter the heart of Tibetan Buddhist culture. Stunning 360-degree mountain views surround you. Visit the ancient Kyanjin Gompa monastery, one of the oldest in the region. Explore the local cheese factory producing yak cheese. Rest of the day for acclimatization and exploration.',
        altitude: '3,870m',
        duration: '3-4 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 5,
        title: 'Kyanjin Gompa: Acclimatization Day',
        description: 'Optional early morning hike to Tserko Ri (4,984m) for spectacular sunrise and panoramic views of Langtang Lirung, Langtang II, Gangchenpo, Naya Kangri, and Tibetan peaks. Alternative: Hike to Kyanjin Ri (4,773m) for equally stunning views with less effort. Or visit Langshisha Kharka for close-up glacier views. Can also explore the village, visit the monastery during prayer time, or simply rest and enjoy the mountain atmosphere.',
        altitude: '3,870m (base) or up to 4,984m',
        duration: '5-7 hours (if hiking)',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 6,
        title: 'Kyanjin Gompa to Lama Hotel (2,380m)',
        description: 'Begin descent retracing your route down the valley. Enjoy different perspectives of the landscape you climbed through. The descent is easier on the legs but watch your knees on the steep sections. Pass through Langtang village and Ghoda Tabela. Continue down through forests back to Lama Hotel. Celebrate your summit success.',
        altitude: '2,380m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 7,
        title: 'Lama Hotel to Syabrubesi and Return to Kathmandu',
        description: 'Final descent through dense forests to Syabrubesi. Cross the last suspension bridges over Langtang Khola. Arrive in Syabrubesi for lunch. After lunch, begin the scenic drive back to Kathmandu. Arrive in Kathmandu evening with wonderful memories of the Langtang region. Optional farewell dinner to celebrate your trek.',
        altitude: '1,450m descending to 1,350m',
        duration: '4-5 hours trek + 7-8 hours drive',
        meals: 'Breakfast, Lunch',
        accommodation: 'N/A',
      },
    ]
  ),
];

//============================================================================
// 2. ANNAPURNA BASE CAMP TREK ITINERARIES
//============================================================================
export const abcItineraries: ItineraryOption[] = [
  createItinerary(
    'abc-10day',
    '10-Day Standard Itinerary',
    10,
    'Perfect balance of trekking and acclimatization to ABC',
    [
      {
        day: 1,
        title: 'Pokhara to Nayapul, Trek to Tikhedhunga (1,540m)',
        description: 'Drive from Pokhara to Nayapul (1.5 hours). Begin trekking following Modi Khola river valley. Pass through beautiful villages and terraced fields. Cross suspension bridge and climb to Tikhedhunga. First day is gentle introduction to the trek.',
        altitude: '1,540m',
        duration: '1.5 hours drive + 3-4 hours trek',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 2,
        title: 'Tikhedhunga to Ghorepani (2,870m)',
        description: 'Climb the famous stone staircase of over 3,000 steps to Ulleri village. Continue through rhododendron and oak forests. Pass through Banthanti and Nangethanti. Final climb to Ghorepani, a charming mountain village with stunning views. Clear evening views of Dhaulagiri and Annapurna ranges.',
        altitude: '2,870m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 3,
        title: 'Ghorepani to Tadapani via Poon Hill (2,630m)',
        description: 'Pre-dawn hike to Poon Hill (3,210m) for spectacular sunrise over Dhaulagiri (8,167m), Annapurna I (8,091m), Machhapuchhre, and other peaks. Return to Ghorepani for breakfast. Trek through rhododendron forests (spectacular in spring) to Tadapani. Views of Annapurna South and Machhapuchhre.',
        altitude: '2,630m',
        duration: '1 hour sunrise hike + 5-6 hours trek',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 4,
        title: 'Tadapani to Chomrong (2,170m)',
        description: 'Descend through beautiful forests with occasional mountain views. Cross Kimrung Khola river on suspension bridge. Climb steep steps up to Chomrong, the last permanent settlement before ABC. Enjoy stunning close-up views of Machhapuchhre (Fishtail) and Annapurna South. Prepare for higher altitude trekking ahead.',
        altitude: '2,170m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 5,
        title: 'Chomrong to Bamboo (2,310m)',
        description: 'Descend steeply to Chomrong Khola. Trek through lush bamboo and rhododendron forests. The trail becomes narrower and more remote. Cross several streams and small waterfalls. Enter the Modi Khola gorge. Reach Bamboo/Dovan area surrounded by towering cliffs and forest.',
        altitude: '2,310m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 6,
        title: 'Bamboo to Deurali (3,230m)',
        description: 'Trek deeper into the Modi Khola gorge through pristine forest. The landscape becomes more alpine. Pass through Himalaya Hotel and Hinku Cave. Cross avalanche-prone areas (safe in trekking seasons). Reach Deurali where trees become sparse. First views into the Annapurna Sanctuary. Temperature drops noticeably.',
        altitude: '3,230m',
        duration: '4-5 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 7,
        title: 'Deurali to Annapurna Base Camp (4,130m)',
        description: 'Enter the Annapurna Sanctuary - a high glacial basin surrounded by towering peaks. Pass Machapuchhre Base Camp (3,700m) with incredible close-up views of the sacred Fishtail mountain. Continue to Annapurna Base Camp surrounded by Annapurna I, III, South, Gangapurna, and other giants. Arrive afternoon with time to explore and photograph. Sunset views are magical.',
        altitude: '4,130m',
        duration: '4-5 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 8,
        title: 'ABC Sunrise and Trek to Bamboo (2,310m)',
        description: 'Wake up for incredible sunrise as golden light illuminates the surrounding peaks. 360-degree panorama of Himalayan giants. After breakfast and final photos, begin long descent back through Deurali and Himalaya Hotel to Bamboo. Dramatic change in landscape and temperature.',
        altitude: '2,310m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 9,
        title: 'Bamboo to Jhinu Danda (1,780m)',
        description: 'Continue descending to Chomrong. Option to take alternative route to Jhinu Danda where natural hot springs await. Soak tired muscles in the therapeutic hot springs by the river. Celebrate completion of your ABC trek.',
        altitude: '1,780m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 10,
        title: 'Jhinu Danda to Nayapul, Drive to Pokhara',
        description: 'Final day of trekking down to Nayapul. Pass through Modi Khola valley and terraced farmlands. Arrive Nayapul and drive back to Pokhara. Arrive afternoon with time to relax by Phewa Lake or explore Lakeside area. Farewell dinner celebrating your achievement.',
        altitude: '820m to 820m',
        duration: '5-6 hours trek + 1.5 hours drive',
        meals: 'Breakfast, Lunch',
        accommodation: 'N/A',
      },
    ]
  ),
];

//============================================================================
// 3. ANNAPURNA CIRCUIT TREK ITINERARIES
//============================================================================
export const circuitItineraries: ItineraryOption[] = [
  createItinerary(
    'circuit-15day',
    '15-Day Classic Circuit',
    15,
    'Complete Annapurna Circuit with proper acclimatization crossing Thorong La Pass',
    [
      {
        day: 1,
        title: 'Drive from Kathmandu/Pokhara to Besisahar, Trek to Bhulbhule (840m)',
        description: 'Scenic drive along the Prithvi Highway through terraced rice paddies and traditional villages. From Besisahar, begin trekking following the Marsyangdi River. Pass through small villages and lush subtropical forests. First day is a gentle warm-up walk to Bhulbhule.',
        altitude: '840m',
        duration: '6-7 hours drive + 1-2 hours trek',
        meals: 'Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 2,
        title: 'Bhulbhule to Jagat (1,300m)',
        description: 'Trek through charming Gurung villages and terraced farmlands. Cross several suspension bridges over the powerful Marsyangdi River. Pass through Ngadi village with views of Manaslu and Himalchuli. The trail alternates between climbs and descents. Reach Jagat, a small settlement at the entrance to the Manang district.',
        altitude: '1,300m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 3,
        title: 'Jagat to Dharapani (1,960m)',
        description: 'Enter a narrow valley with dramatic waterfalls cascading down rocky cliffs. Cross through subtropical forests of rhododendron and oak. Pass through Chamje village and cross a spectacular suspension bridge. Climb through Sattale and Tal village situated beside a beautiful waterfall. Continue to Dharapani where you enter the Manang district officially.',
        altitude: '1,960m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 4,
        title: 'Dharapani to Chame (2,710m)',
        description: 'Trek through beautiful pine and fir forests with occasional glimpses of Manaslu (8,163m) and Annapurna II. The valley widens as you approach Chame, the district headquarters of Manang. Pass through traditional villages with stone houses, prayer wheels, and mani walls. First views of the dramatic Paungda Danda rock face rising 1,500m from the river.',
        altitude: '2,710m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 5,
        title: 'Chame to Pisang (3,300m)',
        description: 'Walk through dense forests with stunning views of Annapurna II and Annapurna IV. Cross suspension bridge and climb through the narrowest section of the valley with vertical cliffs. Pass through Bhratang village and reach the village of Dhukur Pokhari. Spectacular views of Pisang Peak (6,091m) as you approach the village of Pisang with its traditional monastery.',
        altitude: '3,300m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 6,
        title: 'Pisang to Manang (3,540m)',
        description: 'Choice of upper or lower route. Upper route via Ghyaru and Ngawal offers spectacular mountain views and ancient monasteries. Lower route is easier but less scenic. Both routes meet at Mungji before continuing to Manang. The landscape becomes more arid and resembles Tibetan plateau. Manang is a large village with numerous facilities, monasteries, and an airstrip.',
        altitude: '3,540m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 7,
        title: 'Acclimatization Day in Manang',
        description: 'Critical acclimatization day before crossing Thorong La Pass. Options include: Hike to Gangapurna Lake (3,540m) and glacier for stunning reflections. Climb to Praken Gompa monastery (3,950m) or continue to the ice lake (4,600m) for spectacular views. Visit the Himalayan Rescue Association clinic for information on altitude sickness. Explore Manang village and its ancient monasteries. Rest and prepare for the high pass crossing.',
        altitude: '3,540m (base) or up to 4,600m',
        duration: 'Half-day hike (4-6 hours)',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 8,
        title: 'Manang to Yak Kharka (4,110m)',
        description: 'Leave the Marsyangdi Valley and climb steadily through sparse vegetation. The landscape becomes increasingly barren and beautiful. Pass through Tenki village and continue alongside the river. Views of Chulu peaks and Annapurna range. Notice the effects of altitude - thinner air, colder temperatures. Reach Yak Kharka, a small settlement used as summer grazing pastures.',
        altitude: '4,110m',
        duration: '4-5 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 9,
        title: 'Yak Kharka to Thorong Phedi (4,540m)',
        description: 'Trek through alpine desert landscape with dramatic mountain scenery all around. Pass through Ledar with views of Thorong Peak. The trail climbs gradually with increasing views of the Thorong La Pass ahead. Cross several wooden bridges and moraine sections. Reach Thorong Phedi (Base of Thorong) - the last stop before the high pass. Rest, hydrate, and prepare for tomorrow\'s early start.',
        altitude: '4,540m',
        duration: '3-4 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 10,
        title: 'Thorong Phedi to Muktinath via Thorong La Pass (5,416m)',
        description: 'Start very early (3-4 AM) for the challenging climb to Thorong La Pass, the highest point of the trek at 5,416m. Steep zigzag trail with stunning sunrise views over the Himalayas. Spectacular panorama from the pass including Dhaulagiri, Annapurnas, Thorong Peak, and Tibetan plateau. Celebrate at the pass with prayer flags before beginning long descent. Drop 1,600m to Muktinath, a sacred pilgrimage site for both Hindus and Buddhists. Visit the famous Muktinath Temple with its 108 water spouts and eternal flame.',
        altitude: '5,416m at pass, descend to 3,800m',
        duration: '8-10 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 11,
        title: 'Muktinath to Marpha (2,670m)',
        description: 'Descend through the arid Mustang region with dramatically different landscape. Pass through Kagbeni, the gateway to Upper Mustang with its medieval fortress monastery. Trek through the windy Kali Gandaki Gorge, the deepest gorge in the world. Views of Dhaulagiri (8,167m) and Annapurna I (8,091m) towering on either side. Reach Jomsom, a major town with an airport. Continue to Marpha, a beautiful white-washed village famous for apple products.',
        altitude: '2,670m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 12,
        title: 'Marpha to Tatopani (1,190m)',
        description: 'Trek through apple orchards and traditional villages. Pass through Tukuche, once a major trading post on the salt route to Tibet. Views of Dhaulagiri and Nilgiri peaks. The trail descends through varied landscapes from alpine to subtropical. Pass through Kalopani and Ghasa villages. Cross numerous suspension bridges. Reach Tatopani, famous for its natural hot springs. Relax tired muscles in the therapeutic hot springs.',
        altitude: '1,190m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 13,
        title: 'Tatopani to Ghorepani (2,870m)',
        description: 'Major climbing day ascending over 1,600m. Cross suspension bridge over Kali Gandaki River. Climb stone steps through terraced fields and rhododendron forests. Pass through Sikha, Chitre, and several other villages. The final section climbs steeply through beautiful forest to Ghorepani. This classic trekking village offers stunning mountain views and is the gateway to Poon Hill.',
        altitude: '2,870m',
        duration: '7-8 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 14,
        title: 'Ghorepani to Nayapul via Poon Hill, Drive to Pokhara',
        description: 'Pre-dawn hike to Poon Hill (3,210m) for spectacular sunrise panorama over Dhaulagiri, Annapurnas, Machhapuchhre, and Himchuli. One of the most famous viewpoints in Nepal with 360-degree mountain views. Return to Ghorepani for breakfast. Descend through rhododendron forests (spectacular in spring) to Tadapani. Continue steep descent through terraced farmlands to Ghandruk. Final descent to Nayapul. Drive to Pokhara along the Modi Khola valley.',
        altitude: '3,210m at Poon Hill, descend to 820m',
        duration: '1 hour sunrise + 6-7 hours descent + 1.5 hours drive',
        meals: 'Breakfast, Lunch',
        accommodation: 'N/A',
      },
      {
        day: 15,
        title: 'Drive from Pokhara to Kathmandu',
        description: 'Scenic drive back to Kathmandu along the Prithvi Highway. Follow the Trishuli River valley with views of terraced hillsides and traditional villages. Stop at Malekhu or Kurintar for lunch. Arrive in Kathmandu afternoon with time to rest and celebrate completing the Annapurna Circuit. Optional farewell dinner with the team.',
        altitude: '820m to 1,350m',
        duration: '6-7 hours drive',
        meals: 'Breakfast, Lunch',
        accommodation: 'N/A',
      },
    ]
  ),
];

//============================================================================
// 4. EVEREST BASE CAMP TREK ITINERARIES
//============================================================================
export const ebcItineraries: ItineraryOption[] = [
  createItinerary(
    'ebc-14day',
    '14-Day Standard Itinerary',
    14,
    'Classic EBC trek with proper acclimatization and Kala Patthar summit',
    [
      {
        day: 1,
        title: 'Fly Kathmandu to Lukla (2,840m), Trek to Phakding (2,610m)',
        description: 'Thrilling flight to Lukla\'s Tenzing-Hillary Airport, one of the world\'s most challenging airports. Meet your trekking crew and begin the journey. Gentle descent following the Dudh Koshi River through pine forests. Pass through small Sherpa villages with colorful prayer flags. Cross several suspension bridges. First views of mountain peaks. Reach Phakding for the night.',
        altitude: '2,610m',
        duration: '35 min flight + 3-4 hours trek',
        meals: 'Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 2,
        title: 'Phakding to Namche Bazaar (3,440m)',
        description: 'Cross multiple suspension bridges including the famous Hillary Bridge high above the Dudh Koshi River. Trek through beautiful pine and rhododendron forests. Enter Sagarmatha National Park at Monjo. Steep climb of about 600m to Namche Bazaar, the Sherpa capital. If weather is clear, first views of Everest. Namche is a bustling mountain town with shops, bakeries, and internet cafes.',
        altitude: '3,440m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 3,
        title: 'Acclimatization Day in Namche Bazaar',
        description: 'Critical acclimatization day. Morning hike to Everest View Hotel (3,880m) for stunning panorama of Everest, Lhotse, Ama Dablam, and other peaks. Or hike to Khumjung village (3,790m) to visit Edmund Hillary School and the monastery with alleged Yeti scalp. Explore Namche\'s markets, museums, and shops. Visit the Sherpa Culture Museum. Rest and prepare for higher altitude ahead.',
        altitude: '3,440m (base) or up to 3,880m',
        duration: 'Half-day hike (3-4 hours)',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 4,
        title: 'Namche Bazaar to Tengboche (3,870m)',
        description: 'Scenic trail with constant views of Everest, Nuptse, Lhotse, Ama Dablam, Thamserku, and Kwangde. Gradual descent to Phunki Tenga by the river. Steep climb through rhododendron forest to Tengboche. Visit Tengboche Monastery, the largest in the Khumbu region. If timing works, attend evening Buddhist prayer ceremony. Spectacular sunset views of Ama Dablam and Everest from the monastery courtyard.',
        altitude: '3,870m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 5,
        title: 'Tengboche to Dingboche (4,410m)',
        description: 'Descend through birch and rhododendron forests to Deboche. Cross the Imja Khola river and climb to Pangboche, the highest permanent Sherpa settlement with an ancient monastery. Views of Ama Dablam dominating the skyline. The trail opens up to the wide Imja Valley. Pass numerous mani walls and chortens. Reach Dingboche, a summer settlement for yak herders with stunning views of Lhotse and Island Peak.',
        altitude: '4,410m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 6,
        title: 'Acclimatization Day in Dingboche',
        description: 'Important acclimatization day before going higher. Options include: Hike to Nagarjun Hill (5,100m) for spectacular 360-degree views including Makalu, the world\'s fifth highest peak. Or trek toward Chhukung village (4,750m) with close-up views of Island Peak and Lhotse South Face. Both hikes offer excellent acclimatization. Afternoon rest in Dingboche. Prepare gear for the higher sections.',
        altitude: '4,410m (base) or up to 5,100m',
        duration: 'Half-day hike (4-5 hours)',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 7,
        title: 'Dingboche to Lobuche (4,940m)',
        description: 'Trek along the lateral moraine of the Khumbu Glacier. Pass through Dughla (Thukla) where you stop for tea. Steep climb to the memorials of climbers who have perished on Everest, including Scott Fischer and many Sherpas. Touching reminder of the mountains\' power. Continue along the glacier among spectacular ice formations. Reach Lobuche with dramatic views of Nuptse and Pumori.',
        altitude: '4,940m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 8,
        title: 'Lobuche to Gorak Shep (5,170m), Hike to Everest Base Camp (5,364m)',
        description: 'Trek across the Khumbu Glacier moraine on rocky, undulating trail. Reach Gorak Shep, the last teahouse settlement and former base camp site. Drop bags and have lunch. Afternoon hike to Everest Base Camp through glacier moraine. During climbing season (April-May), see colorful expedition tents. Stand at the foot of the Khumbu Icefall. Return to Gorak Shep for the night. Challenging day at high altitude but incredibly rewarding.',
        altitude: '5,364m at EBC, return to 5,170m',
        duration: '8-9 hours total',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 9,
        title: 'Gorak Shep to Kala Patthar (5,545m), Descend to Pheriche (4,280m)',
        description: 'Very early pre-dawn start for sunrise hike to Kala Patthar, the best viewpoint for Everest. Steep climb in darkness using headlamps. Reach the summit for spectacular sunrise illuminating Everest, Nuptse, Changtse, Pumori, and countless other peaks. Best close-up views of Everest you\'ll get without climbing it. Return to Gorak Shep for breakfast. Long descent to Pheriche, losing over 1,200m altitude. Body will appreciate the thicker air.',
        altitude: '5,545m at Kala Patthar, descend to 4,280m',
        duration: '8-9 hours total',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 10,
        title: 'Pheriche to Namche Bazaar (3,440m)',
        description: 'Long but pleasant descent day. Trek through Pangboche and across the river. Climb back up to Tengboche for last views of Ama Dablam. Descend through forests to Phunki Tenga. Final climb back up to Namche Bazaar. Celebrate your achievement with hot shower, bakery treats, and WiFi. Your body will feel the benefits of lower altitude.',
        altitude: '3,440m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 11,
        title: 'Namche Bazaar to Lukla (2,840m)',
        description: 'Final day of trekking. Descend from Namche with great views back up the valley. Cross the high Hillary Bridge and follow familiar trail through Monjo and Phakding. Reflect on the incredible journey. Pass through villages you barely noticed on the way up. Arrive in Lukla and celebrate with your trekking crew. Traditional Sherpa party with local chang (beer) and dancing.',
        altitude: '2,840m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 12,
        title: 'Fly Lukla to Kathmandu',
        description: 'Morning flight from Lukla back to Kathmandu (weather permitting - flights can be delayed). Enjoy last aerial views of the mountains. Arrive in Kathmandu and transfer to hotel. Rest of the day free for shopping, relaxation, or exploring Kathmandu. Optional farewell dinner celebrating your Everest Base Camp achievement.',
        altitude: '1,350m',
        duration: '35 min flight',
        meals: 'Breakfast',
        accommodation: 'N/A',
      },
      {
        day: 13,
        title: 'Buffer Day in Kathmandu',
        description: 'Buffer day for flight delays from Lukla (common due to weather). If flights operated on time, use this day for sightseeing in Kathmandu Valley. Visit Pashupatinath Temple, Boudhanath Stupa, Swayambhunath (Monkey Temple), or Durbar Square. Shopping for souvenirs in Thamel. Massage and spa to recover from trek. Final preparations for departure.',
        altitude: '1,350m',
        duration: 'Flexible',
        meals: 'Breakfast',
        accommodation: 'N/A',
      },
      {
        day: 14,
        title: 'Final Departure or Extension',
        description: 'Transfer to airport for international departure. Or begin additional adventures in Nepal - jungle safari in Chitwan, rafting, Pokhara relaxation, or another trek. Extensions can be arranged for Gokyo Lakes, Three Passes, or other routes.',
        altitude: '1,350m',
        duration: 'As per flight schedule',
        meals: 'Breakfast',
        accommodation: 'N/A',
      },
    ]
  ),
];

//============================================================================
// 5. MANASLU CIRCUIT TREK ITINERARIES
//============================================================================
export const manasluItineraries: ItineraryOption[] = [
  createItinerary(
    'manaslu-15day',
    '15-Day Standard Circuit',
    15,
    'Complete Manaslu Circuit with Larkya La Pass crossing, off-the-beaten-path adventure',
    [
      {
        day: 1,
        title: 'Drive Kathmandu to Soti Khola (710m)',
        description: 'Early morning drive from Kathmandu along the Prithvi Highway toward Pokhara. Turn north at Dhading Besi and continue through terraced hills and traditional villages. Pass through Arughat, the starting point of the Manaslu Circuit. Continue along the Budhi Gandaki River valley on rough roads. Reach Soti Khola, a small village marking the official trek start.',
        altitude: '710m',
        duration: '7-8 hours drive',
        meals: 'Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 2,
        title: 'Soti Khola to Machha Khola (930m)',
        description: 'Trek begins following the Budhi Gandaki River through subtropical forests. Trail alternates between climbing and descending over ridges. Cross several suspension bridges. Pass through small villages and terraced fields. Walk through dense sal forests. Cross a suspension bridge and climb over another ridge to reach Machha Khola village beside the river.',
        altitude: '930m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 3,
        title: 'Machha Khola to Jagat (1,410m)',
        description: 'Narrow trail carved into the cliff face high above the river. Cross several suspension bridges back and forth across the Budhi Gandaki. Pass through Khorlabesi village and hot springs. Climb through terraced fields and past waterfalls. Cross into the Manaslu Conservation Area at Jagat. The village sits at the confluence of two rivers with dramatic gorge views.',
        altitude: '1,410m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 4,
        title: 'Jagat to Deng (1,860m)',
        description: 'Trail climbs through rocky terrain and forest. Cross several suspension bridges with stunning valley views. Pass through Salleri and Sirdibas villages. Enter deeper canyon with vertical rock walls. Notice increasing Buddhist influence with mani walls and prayer flags. Reach Philim, a large Gurung village. Continue through narrow gorge to Deng, where Tibetan culture becomes more prominent.',
        altitude: '1,860m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 5,
        title: 'Deng to Namrung (2,630m)',
        description: 'Cross the Budhi Gandaki and climb through forests of pine and rhododendron. Pass through Rana village with its gompa and mani walls. The landscape opens up with first views of Manaslu. Trek through bamboo and rhododendron forests. Pass through Bihi Phedi and cross bridge. Climb to Namrung, a beautiful Tibetan village with traditional stone houses. Excellent views of Ganesh Himal and Siringi Himal.',
        altitude: '2,630m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 6,
        title: 'Namrung to Samagaun (3,530m)',
        description: 'Spectacular trekking day with continuous mountain views. Pass through Lihi and Sho villages with traditional Tibetan architecture. Trek through forests and across several streams. Views of Manaslu, Ganesh Himal, and Himalchuli. Pass through Lho village with its beautiful monastery. Visit the monastery for panoramic mountain views. Continue to Samagaun, a large Tibetan village with a gompa. Spectacular views of Manaslu\'s north face and surrounding glaciers.',
        altitude: '3,530m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 7,
        title: 'Acclimatization Day in Samagaun',
        description: 'Important acclimatization before crossing Larkya La Pass. Options include: Hike to Manaslu Base Camp (4,800m) or Birendra Lake through yak pastures and moraine. Visit Pungyen Gompa monastery perched on a hill above the village with incredible mountain views. Explore Samagaun village and its Tibetan culture, mani walls, and chortens. Rest and prepare gear for the high pass crossing ahead.',
        altitude: '3,530m (base) or up to 4,800m',
        duration: 'Half-day hike (4-6 hours)',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 8,
        title: 'Samagaun to Samdo (3,860m)',
        description: 'Relatively short day to aid acclimatization. Trek through alpine landscape with views of Tibetan border peaks. Cross streams and walk through juniper scrub. Pass ancient mani walls and chortens. Reach Samdo, the last village before the pass. This was once an important trading post with Tibet. Excellent views of peaks on the Tibet border. Prepare for the pass crossing.',
        altitude: '3,860m',
        duration: '3-4 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 9,
        title: 'Samdo to Dharamsala/Larkya Phedi (4,460m)',
        description: 'Trek through yak pastures with spectacular views. Cross several wooden bridges over glacial streams. Trail climbs gradually through alpine desert landscape. Pass frozen waterfalls and enter a glacial valley. Views of Larkya Glacier and surrounding peaks. Reach Dharamsala (also called Larkya Phedi), basic accommodation at the base of the pass. Rest, hydrate, and go to bed early for tomorrow\'s pre-dawn start.',
        altitude: '4,460m',
        duration: '4-5 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 10,
        title: 'Dharamsala to Bimthang via Larkya La Pass (5,160m)',
        description: 'Start before dawn (3-4 AM) for the challenging climb to Larkya La Pass. Trek through glacier moraine and frozen landscapes. Steep climb with stunning sunrise views. Reach Larkya La Pass (5,160m), the highest point of the trek. Incredible panorama of Himlung Himal, Cheo Himal, Kang Guru, Annapurna II, and countless peaks. Prayer flags mark the pass. Long descent losing over 1,600m to Bimthang through varied terrain. Dramatic change from alpine desert to green pastures.',
        altitude: '5,160m at pass, descend to 3,590m',
        duration: '8-10 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 11,
        title: 'Bimthang to Dharapani (1,960m)',
        description: 'Long descent day through changing landscapes. Pass through high pastures and rhododendron forests. Views of Manaslu, Lamjung Himal, and Annapurna II. Cross several streams and through beautiful forests. Pass through Karche village. Descend through Gho village to finally reach Dharapani where you join the Annapurna Circuit trail. Major altitude loss - your body will appreciate the thicker air.',
        altitude: '1,960m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 12,
        title: 'Dharapani to Jagat (1,300m)',
        description: 'Retrace steps from the Annapurna Circuit trek. Descend through forests and terraced fields. Cross suspension bridges over the Marsyangdi River. Pass through Tal village with its waterfall. Continue through Chamje and Sattale. Cross dramatic bridges in the narrow canyon. Reach Jagat for the night. Celebrate completing the Manaslu Circuit.',
        altitude: '1,300m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 13,
        title: 'Jagat to Syange, Drive to Kathmandu',
        description: 'Final trekking day descending to Syange. Pass through familiar villages from the beginning of the trek. Cross final suspension bridges. Reach Syange where the road begins. Meet your vehicle for the drive back to Kathmandu. Drive along the Marsyangdi and then Trishuli rivers. Arrive in Kathmandu evening. Hot shower and comfortable bed await.',
        altitude: '1,100m to 1,350m',
        duration: '3-4 hours trek + 7-8 hours drive',
        meals: 'Breakfast, Lunch',
        accommodation: 'N/A',
      },
      {
        day: 14,
        title: 'Buffer Day in Kathmandu',
        description: 'Buffer day for any delays during the trek or drive. If schedule went smoothly, use this day for rest, shopping in Thamel, visiting cultural sites like Pashupatinath or Boudhanath, or spa treatments. Process photos and memories from the incredible Manaslu Circuit.',
        altitude: '1,350m',
        duration: 'Flexible',
        meals: 'Breakfast',
        accommodation: 'N/A',
      },
      {
        day: 15,
        title: 'Final Departure',
        description: 'Transfer to airport for international departure. Or extend your Nepal adventure with Chitwan jungle safari, Pokhara relaxation, or another trek. We can arrange any extension activities.',
        altitude: '1,350m',
        duration: 'As per flight schedule',
        meals: 'Breakfast',
        accommodation: 'N/A',
      },
    ]
  ),
];

//============================================================================
// 6. GHOREPANI POON HILL TREK ITINERARIES
//============================================================================
export const poonHillItineraries: ItineraryOption[] = [
  createItinerary(
    'poonhill-5day',
    '5-Day Standard Itinerary',
    5,
    'Short but spectacular trek featuring the famous Poon Hill sunrise panorama',
    [
      {
        day: 1,
        title: 'Pokhara to Nayapul, Trek to Tikhedhunga (1,540m)',
        description: 'Drive from Pokhara to Nayapul (1.5 hours) through beautiful countryside. Begin trekking following the Modi Khola river. Pass through charming villages and terraced rice paddies. Cross suspension bridge and climb gradually to Birethanti, the entrance to the Annapurna Conservation Area. Continue along the river and then climb to Tikhedhunga. First day is a warm-up for tomorrow\'s big climb.',
        altitude: '1,540m',
        duration: '1.5 hours drive + 3-4 hours trek',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 2,
        title: 'Tikhedhunga to Ghorepani (2,870m)',
        description: 'Challenging day climbing the famous stone staircase with over 3,000 steps. Steep ascent through beautiful forests passing several tea houses. Reach Ulleri village, a large Magar settlement. Continue climbing through rhododendron and oak forests (spectacular in spring when rhododendrons bloom). Pass through Banthanti and Nangethanti villages. Final push to Ghorepani through beautiful forest. Arrive with stunning views of Annapurna South, Nilgiri, and Dhaulagiri.',
        altitude: '2,870m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 3,
        title: 'Ghorepani to Tadapani via Poon Hill (2,630m)',
        description: 'Wake up early (around 4:30 AM) for the pre-dawn hike to Poon Hill (3,210m). Climb about 300m in darkness using headlamps with hundreds of other trekkers. Watch spectacular sunrise over the Himalayas - one of Nepal\'s most famous viewpoints. 360-degree panorama including Dhaulagiri (8,167m), Annapurna I (8,091m), Annapurna South, Nilgiri, Machhapuchhre, Lamjung Himal, and Himchuli. Return to Ghorepani for breakfast. Trek through magnificent rhododendron forests to Tadapani with occasional mountain views.',
        altitude: '3,210m at Poon Hill, trek to 2,630m',
        duration: '1 hour sunrise hike + 5-6 hours trek',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 4,
        title: 'Tadapani to Ghandruk (1,940m)',
        description: 'Beautiful forest walk through rhododendron, oak, and bamboo. Gradual descent with occasional climbs over ridges. Views of Annapurna South, Hiunchuli, and Machhapuchhre (Fishtail). Cross several streams and through small settlements. Reach Ghandruk, one of the largest Gurung villages in Nepal. Visit the Gurung Museum to learn about local culture. Spectacular evening views of Annapurna South and Machhapuchhre from the village.',
        altitude: '1,940m',
        duration: '4-5 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 5,
        title: 'Ghandruk to Nayapul, Drive to Pokhara',
        description: 'Final day descending through terraced farmlands and traditional villages. Pass stone houses with slate roofs. Trek through Modi Khola valley with views of surrounding hills. Long descent of about 600m through stone steps and paths. Reach Kimche and continue to Nayapul. Meet your vehicle for the drive back to Pokhara. Arrive in Pokhara with time to relax by Phewa Lake or explore Lakeside. Optional farewell dinner celebrating your trek.',
        altitude: '820m',
        duration: '5-6 hours trek + 1.5 hours drive',
        meals: 'Breakfast, Lunch',
        accommodation: 'N/A',
      },
    ]
  ),
];

//============================================================================
// 7. UPPER MUSTANG TREK ITINERARIES
//============================================================================
export const mustangItineraries: ItineraryOption[] = [
  createItinerary(
    'mustang-12day',
    '12-Day Standard Itinerary',
    12,
    'Journey to the forbidden kingdom - ancient Tibetan culture and dramatic desert landscapes',
    [
      {
        day: 1,
        title: 'Pokhara to Jomsom (2,720m)',
        description: 'Early morning flight from Pokhara to Jomsom through the world\'s deepest gorge. Spectacular aerial views of Dhaulagiri and Annapurna ranges. Twenty-minute flight lands at Jomsom, the gateway to Upper Mustang. Explore Jomsom town and prepare permits. Short acclimatization hike around the area. Visit local monasteries and markets. Prepare for the Upper Mustang adventure.',
        altitude: '2,720m',
        duration: '20 min flight + exploration',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 2,
        title: 'Jomsom to Kagbeni (2,800m)',
        description: 'Trek along the Kali Gandaki River through dramatic landscape. Walk through apple orchards and barley fields. Pass through Ekle Bhatti village. Reach Kagbeni, the gateway to Upper Mustang. Medieval village with narrow alleys, ancient monastery, and fortress. Check permits at the checkpoint. Explore the village\'s ancient architecture and Kag Chode Thupten Samphel Ling monastery. Views of Nilgiri across the valley.',
        altitude: '2,800m',
        duration: '3-4 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 3,
        title: 'Kagbeni to Chele (3,050m)',
        description: 'Enter restricted Upper Mustang region. Trek along the Kali Gandaki River through increasingly barren landscape. Pass through Tangbe village with its maze of narrow alleys and white-washed houses. Continue to Chhusang and cross suspension bridge. Trek through dramatic canyon with layered rock formations in reds, yellows, and browns. Climb steep trail to Chele village. Tibetan culture becomes predominant.',
        altitude: '3,050m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 4,
        title: 'Chele to Syanbochen (3,800m)',
        description: 'Climb out of Chele to a plateau with panoramic mountain views. Trek through high desert landscape with bizarre rock formations. Cross several passes including Taklam La (3,624m) and Dajori La (3,735m). Descent to Samar village in a hidden valley. Climb to another ridge and descend to Syanbochen. Landscape resembles Tibetan plateau with prayer flags and mani walls. Spectacular sunset views.',
        altitude: '3,800m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 5,
        title: 'Syanbochen to Ghami (3,520m)',
        description: 'Trek through arid landscape with stunning rock formations. Cross Yamda La pass (3,850m) with views of Damodar Himal and Annapurna ranges. Descend through Geling village, one of the largest villages in Upper Mustang. Visit the ancient monastery with rare murals. Continue across the valley and climb to Nyi La pass (4,010m). Long descent to Ghami village. Visit the magnificent 300-meter-long mani wall, one of the longest in Nepal.',
        altitude: '3,520m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 6,
        title: 'Ghami to Tsarang (3,560m)',
        description: 'Cross Tsarang La pass (3,870m) with spectacular mountain panoramas. Trek through dramatic canyon with layered rock formations. Enter fertile Tsarang valley, a surprising oasis in the desert landscape. Reach Tsarang, the second-largest village in Mustang. Visit the impressive Tsarang Monastery with ancient murals and statues. Explore the old palace and village. Spectacular views of Nilgiri and Dhaulagiri.',
        altitude: '3,560m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 7,
        title: 'Tsarang to Lo Manthang (3,840m)',
        description: 'Trek through the valley with views of Tsarang monastery perched on the cliff. Climb gradually to Lo La pass (3,950m). First views of the walled city of Lo Manthang. Descend to the capital of the former Kingdom of Lo. Enter through the gates into the medieval walled city. Explore the narrow lanes, ancient palaces, and monasteries. Visit the Raja\'s palace (if permitted). Evening exploration of the mystical walled city.',
        altitude: '3,840m',
        duration: '4-5 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 8,
        title: 'Exploration Day in Lo Manthang',
        description: 'Full day exploring the walled city and surrounding areas. Visit Champa Lhakhang (God house), Thubchen Gompa with rare murals, and Chyodi Gompa. Optional day hike to Chhoser village with ancient cave dwellings carved into cliffs (3-4 hours). Or visit Namgyal Monastery and the border with Tibet. Interact with locals and learn about their unique culture preserved for centuries. Visit the monastery during prayer ceremonies. Explore the medieval architecture and daily life in this time capsule.',
        altitude: '3,840m (or up to 4,000m)',
        duration: 'Full day exploration',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 9,
        title: 'Lo Manthang to Drakmar (3,810m)',
        description: 'Alternative return route through different landscapes. Trek east from Lo Manthang through the Mustang plateau. Cross small passes with views of Tibetan peaks. Reach Drakmar village famous for its red cliffs and rock formations. Visit the cliff-face monastery. Explore caves carved into the red cliffs. Different perspective of the Mustang landscape. Quieter route with fewer trekkers.',
        altitude: '3,810m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 10,
        title: 'Drakmar to Ghiling (3,806m)',
        description: 'Trek through dramatic red cliffs and desert landscape. Cross several passes with mountain views. Pass ancient chortens and mani walls. Reach Ghiling village, a small agricultural settlement. Visit the local monastery. Experience authentic village life away from main routes. Spectacular sunset over the dramatic landscape.',
        altitude: '3,806m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 11,
        title: 'Ghiling to Chhusang (2,980m)',
        description: 'Retrace route through Syanbochen and Samar. Cross the familiar passes with different lighting and perspectives. Long descent through Chele and down to Chhusang. Last evening in Upper Mustang region. Reflect on the incredible journey through the forbidden kingdom.',
        altitude: '2,980m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 12,
        title: 'Chhusang to Jomsom (2,720m), Fly to Pokhara',
        description: 'Final trekking day back to Jomsom through Kagbeni. Pass through familiar territory with new appreciation. Reach Jomsom and catch afternoon flight to Pokhara (weather permitting). If flight delayed, overnight in Jomsom. Return to Pokhara civilization with incredible memories of the ancient kingdom. Farewell dinner celebrating your Upper Mustang adventure.',
        altitude: '2,720m to 820m',
        duration: '4-5 hours trek + 20 min flight',
        meals: 'Breakfast, Lunch',
        accommodation: 'N/A',
      },
    ]
  ),
];

// Export itineraries by trek slug
export const allTrekItineraries: { [key: string]: ItineraryOption[] } = {
  'langtang-trek': langtangItineraries,
  'annapurna-base-camp': abcItineraries,
  'annapurna-circuit': circuitItineraries,
  'everest-base-camp': ebcItineraries,
  'manaslu-circuit': manasluItineraries,
  'ghorepani-poon-hill': poonHillItineraries,
  'upper-mustang': mustangItineraries,
};
