import { ItineraryOption } from '@/types';

// Langtang Trek Itineraries
export const langtangItineraries: ItineraryOption[] = [
  {
    id: 'langtang-7day',
    name: '7-Day Standard Itinerary',
    days: 7,
    description: 'Classic Langtang Valley trek with optimal acclimatization',
    itinerary: [
      {
        day: 1,
        title: 'Kathmandu to Syabrubesi',
        description: 'Scenic drive from Kathmandu through winding mountain roads, passing through traditional Tamang and Sherpa villages. The route offers beautiful views of terraced fields and the Langtang range.',
        altitude: '1,450m',
        duration: '7-8 hours drive',
        meals: 'Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 2,
        title: 'Syabrubesi to Lama Hotel',
        description: 'Trek begins through subtropical forests along the Langtang Khola. Cross suspension bridges and climb through dense forests of oak and rhododendron. Watch for red pandas and langur monkeys.',
        altitude: '2,380m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 3,
        title: 'Lama Hotel to Langtang Village',
        description: 'Continue ascending through beautiful forests with occasional glimpses of Langtang Lirung. The trail opens up as you reach Ghoda Tabela, offering the first spectacular mountain views. Pass through the restored Langtang village.',
        altitude: '3,430m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 4,
        title: 'Langtang Village to Kyanjin Gompa',
        description: 'Walk through yak pastures and traditional stone houses with stunning mountain views all around. Visit the ancient Buddhist monastery and cheese factory. Explore the village and acclimatize.',
        altitude: '3,870m',
        duration: '3-4 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 5,
        title: 'Kyanjin Gompa: Acclimatization and Exploration',
        description: 'Optional hike to Tserko Ri (4,984m) for panoramic Himalayan views or visit Kyanjin Ri (4,773m). Both viewpoints offer spectacular sunrise views. Alternatively, hike to Langshisha Kharka or relax and explore the village.',
        altitude: '3,870m (or up to 4,984m)',
        duration: '5-7 hours (if hiking)',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 6,
        title: 'Kyanjin Gompa to Lama Hotel',
        description: 'Retrace your steps down the valley, enjoying different perspectives of the landscape. Descend through forests and meadows back to Lama Hotel.',
        altitude: '2,380m',
        duration: '6-7 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 7,
        title: 'Lama Hotel to Syabrubesi and Drive to Kathmandu',
        description: 'Final descent through forests to Syabrubesi. After lunch, drive back to Kathmandu, arriving in the evening with memories of your Himalayan adventure.',
        altitude: '1,450m to 1,350m',
        duration: '4-5 hours trek + 7-8 hours drive',
        meals: 'Breakfast, Lunch',
        accommodation: 'N/A',
      },
    ],
  },
  {
    id: 'langtang-10day',
    name: '10-Day Extended Itinerary',
    days: 10,
    description: 'Extended trek with more acclimatization and exploration time',
    itinerary: [
      {
        day: 1,
        title: 'Kathmandu to Syabrubesi',
        description: 'Scenic 7-8 hour drive through beautiful countryside, passing traditional villages and terraced fields.',
        altitude: '1,450m',
        duration: '7-8 hours',
        meals: 'Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 2,
        title: 'Syabrubesi to Lama Hotel',
        description: 'Begin trekking through lush forests along Langtang River, crossing several suspension bridges.',
        altitude: '2,380m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 3,
        title: 'Lama Hotel to Ghoda Tabela',
        description: 'Trek through rhododendron and bamboo forests with increasing mountain views.',
        altitude: '3,020m',
        duration: '4-5 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 4,
        title: 'Ghoda Tabela to Langtang Village',
        description: 'Continue ascending with spectacular views of Langtang Lirung. Visit the rebuilt village and interact with locals.',
        altitude: '3,430m',
        duration: '3-4 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 5,
        title: 'Langtang Village to Kyanjin Gompa',
        description: 'Gradual climb through yak pastures with 360-degree mountain views. Visit monastery and cheese factory.',
        altitude: '3,870m',
        duration: '3-4 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 6,
        title: 'Kyanjin Gompa: Hike to Tserko Ri',
        description: 'Early morning hike to Tserko Ri summit for breathtaking sunrise over Langtang, Gangchhenpo, and Tibetan peaks.',
        altitude: '4,984m (summit)',
        duration: '7-8 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 7,
        title: 'Kyanjin Gompa: Explore Langshisha Kharka',
        description: 'Optional hike to Langshisha Kharka for closer views of glaciers or rest day for acclimatization.',
        altitude: '3,870m (or 4,200m)',
        duration: '4-5 hours (if hiking)',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 8,
        title: 'Kyanjin Gompa to Langtang Village',
        description: 'Descend back to Langtang Village, enjoying the scenery from a different perspective.',
        altitude: '3,430m',
        duration: '3-4 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 9,
        title: 'Langtang Village to Lama Hotel',
        description: 'Continue descent through forests, arriving at Lama Hotel in the afternoon.',
        altitude: '2,380m',
        duration: '5-6 hours',
        meals: 'Breakfast, Lunch, Dinner',
        accommodation: 'Teahouse',
      },
      {
        day: 10,
        title: 'Lama Hotel to Syabrubesi and Drive to Kathmandu',
        description: 'Final trek down to Syabrubesi followed by drive back to Kathmandu.',
        altitude: '1,450m to 1,350m',
        duration: '4-5 hours trek + 7-8 hours drive',
        meals: 'Breakfast, Lunch',
        accommodation: 'N/A',
      },
    ],
  },
];

// Continue with more trek itineraries...
// (File will be very long, so I'll create this systematically)
